# Server
server:
  servlet:
    context-path: /catalog

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /v3/api-docs
  show-actuator: true

# actuator
management:
  endpoints:
    web:
      exposure:
        include: liveness, readiness, health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


# data base
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalog_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:newPassword1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type_contributors:
          - com.overengineeredecommerce.domain.entity.JsonTypeContributor